host: "your_private_ip:5601"

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["your_private_ip:9200"]

  # Protocol - either `http` (default) or `https`.
  #protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  # replace the below with you own credentials
  username: "elastic"
  password: "6kNbsxQGYZ2EQJiqJpgl"


